### ISSUE TITLE
Finish report #1

### ISSUE THREAD

**Issue by IoanaCiornei** [android-iot/gnu#6]
Before continuing with our research, we should finish all the work that is included in report#1:

- [ ] define more complex scenarios (media streaming)
- [ ] install and run the necessary software in ArchLinux
- [ ] test the scenarios with the Monsoon Power Monitor
- [ ] rewrite documentation
